### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException

### ISSUE THREAD

**Issue by patelhenil** [nicolomantini/LinkedIn-Easy-Apply-Bot#1]
Hi Nicolo, appreciate your code. When running quickstart.py or easyapplybot.py directly there seems to be a selenium.common.exceptions.NoSuchElementException. Attaching a screenshot of the issue. Your input would be appreciated. Thanks.
![Capture](https://user-images.githubusercontent.com/33011641/57588889-80494c00-74e9-11e9-886a-3c9b7e045df2.PNG)

**Comment by patelhenil** [comment]
I think the code is a bit outdated as LinkedIn have changed their UI and some of their id and class tags.

**Comment by nicolomantini** [comment]
Hi
Yes you are right, Linkedin has recently modified the UI, therefore the code is failing when trying to trigger a button that does not exists anymore... The button was only supposed to list the jobs in a unique column (instead of 2 as it is by default). That was done to simplify the scraping, but it is not necessary to do it in that way.
It should be quite straight forward to update the code, removing the old button trigger (line 117 and 118) and updating the part that gets the links of the jobs in the page. If that gets updated, the rest should follow.

# get job links
links = self.browser.find_elements_by_xpath(
                    '//div[@data-job-id]'
                    )

If you have time to update it you are more than welcome to submit a pull request :))

Best
Nico

**Comment by nicolomantini** [comment]
The code has been updated
