### ISSUE TITLE
The Program doesnt really apply. It get the jobs and log cannot apply to this job

### ISSUE THREAD

**Issue by ronnieotieno** [nicolomantini/LinkedIn-Easy-Apply-Bot#14]

**Comment by krapes** [comment]
Hey @ronnieotieno,

I've fixed the errors so that it now applies to job. Before as you mentioned, it did not know how to handle the new button structure of "Next", "Review", "Submit".

I submitted a pull request to this repo [Here](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/pull/19)

Or you can download it from 
https://github.com/krapes/LinkedIn-Easy-Apply-Bot.git
