### ISSUE TITLE
Bot consult offers but fail to apply 

### ISSUE THREAD

**Issue by Farouk615** [nicolomantini/LinkedIn-Easy-Apply-Bot#175]
I ve set up the bot, everything works great, when i launch it chrome opens and linkedin is opened and I see offers are being consulted but never applied, at this stage before cliking the easy apply button, I get this error 

`[23132:18516:0725/132841.970:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
what is this error` 

sometimes I get this also 
`[18056:23432:0725/133745.577:ERROR:cert_issuer_source_aia.cc(35)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate`

any help ?

**Comment by TechWithTy** [comment]
Here's a reply to address the issues you're encountering with the bot:

---

It looks like you're encountering a couple of errors while running the bot:

1. **STUN Server Resolution Error**:
   
   ```
   [23132:18516:0725/132841.970:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
   ```

   This error indicates that the bot is unable to resolve the address for the STUN server (`stun.l.google.com`). STUN servers are typically used for WebRTC to determine the public IP address. This error might not directly affect the bot's ability to apply for jobs, but it can indicate network resolution issues.

   **Possible solutions**:
   - Ensure your DNS settings are correctly configured.
   - Check if there's any firewall or network restriction blocking the STUN server.
   - Sometimes, this error can be safely ignored if the bot's primary functionality is unaffected.

2. **Certificate Parsing Error**:

   ```
   [18056:23432:0725/133745.577:ERROR:cert_issuer_source_aia.cc(35)] Error parsing cert retrieved from AIA (as DER): ERROR: Couldn't read tbsCertificate as SEQUENCE ERROR: Failed parsing Certificate
   ```

   This error suggests there was an issue parsing a certificate retrieved from an AIA (Authority Information Access) location. This might be due to:
   - An invalid or malformed certificate.
   - A temporary network issue that affected the certificate retrieval.

   **Possible solutions**:
   - Ensure your system's date and time are correctly set, as incorrect settings can cause certificate errors.
   - Verify that your network connection is stable and not blocking access to certificate authorities.
   - Check for any software or browser updates that might resolve these issues.

3. **Bot Not Applying for Jobs**:

   Even if these errors appear, they shouldn't prevent the bot from clicking the "Easy Apply" button if everything else is set up correctly. If the bot is not applying for jobs, consider the following steps:
   - **Debugging**: Add more logging to your script to understand where it might be failing. Ensure the bot correctly identifies and interacts with the "Easy Apply" button.
   - **Selectors**: Verify that the selectors used to identify the "Easy Apply" button and other elements are correct and up to date with LinkedIn's latest HTML structure.
   - **Delays**: Introduce delays between actions to ensure the page has fully loaded before the bot tries to interact with elements. This can help avoid timing issues where the bot tries to click a button that hasn't fully rendered yet.

   Here's a quick example to add more logging and delay:

   ```python
   import time
   import logging

   logging.basicConfig(level=logging.INFO)

   def apply_for_jobs(driver):
       try:
           logging.info("Looking for the Easy Apply button...")
           easy_apply_button = driver.find_element_by_css_selector('button[aria-label="Easy Apply"]')
           if easy_apply_button:
               logging.info("Easy Apply button found, clicking...")
               easy_apply_button.click()
               time.sleep(2)  # Wait for 2 seconds to ensure the action is complete
           else:
               logging.warning("Easy Apply button not found!")
       except Exception as e:
           logging.error(f"An error occurred: {e}")
   ```

   By adding logging and delays, you can better understand the bot's behavior and identify where it might be going wrong.

If you continue experiencing issues, please provide more details or logs, and we can assist you further.
