### ISSUE TITLE
Unable to Apply

### ISSUE THREAD

**Issue by ronnieotieno** [nicolomantini/LinkedIn-Easy-Apply-Bot#29]
@krapes Whenever I run the new updated version I get this error
![image](https://user-images.githubusercontent.com/48311117/87443007-a1319380-c5fd-11ea-92ef-b577d974dbce.png)

**Comment by krapes** [comment]
Hey @ronnieotieno,

The issue was there was a '-' in your config file under `output_file` but there was no string indicating a filename. I've adjusted the parsing of the config file to be able to handle this situation in [this pull request](https://github.com/nicolomantini/LinkedIn-Easy-Apply-Bot/pull/31)

**Comment by ronnieotieno** [comment]
Thanks @krapes however, I have another issue, the program doesn't go to next page. it terminates and chrome LinkedIn tab disappears 
![image](https://user-images.githubusercontent.com/48311117/87872362-7e69fb00-c9c0-11ea-8ef7-a47199547f24.png)

**Comment by krapes** [comment]
The `data;` indicates that the program as not yet entered the login page. 

Most likely an issue with the configuration and/or the loading of the output file
